---

- hosts: all
  become: true
  pre_tasks:

  - name: UPDATE Ubuntu
    tags: update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: UPDATE CentOS
    tags: update
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: Control_servers
  become: true
  tasks:

  - name: Copy
    run_once: yes
    fetch: src=/var/log/messages dest=logfiles/ flat=yes
    when: inventory_hostname == "192.168.56.103"

- hosts: Manage_servers
  become: true
  tasks:

  - name: Output
    copy: src=logfiles/messages dest=~/AnsibleforLogFiles/
    when: inventory_hostname == "192.168.56.102"


